param(
    [Parameter(Mandatory = $true)]
    [string]$Version,

    [Parameter(Mandatory = $false)]
    [string]$ConfigPath = "scripts/release/installer.config.json",

    [Parameter(Mandatory = $false)]
    [string]$OutputDirectory = "artifacts/installer"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ($Version -notmatch "^\d+\.\d+\.\d+$")
{
    throw "Version '$Version' is not a valid SemVer (X.Y.Z)."
}

if (-not (Test-Path -LiteralPath $ConfigPath))
{
    throw "Installer config file was not found at '$ConfigPath'."
}

$config = Get-Content -LiteralPath $ConfigPath -Raw | ConvertFrom-Json

if ([string]::IsNullOrWhiteSpace($config.productName))
{
    throw "Installer config requires 'productName'."
}

if ([string]::IsNullOrWhiteSpace($config.architecture))
{
    throw "Installer config requires 'architecture'."
}

if ([string]::IsNullOrWhiteSpace($config.runtimeIdentifier))
{
    throw "Installer config requires 'runtimeIdentifier'."
}

if ([string]::IsNullOrWhiteSpace($config.publishProject))
{
    throw "Installer config requires 'publishProject'."
}

if ([string]::IsNullOrWhiteSpace($config.publishConfiguration))
{
    throw "Installer config requires 'publishConfiguration'."
}

$artifactBaseName = "{0}-v{1}-win-{2}-installer" -f $config.productName, $Version, $config.architecture

$publishDirectory = Join-Path $OutputDirectory "publish"
$packageDirectory = Join-Path $OutputDirectory "package"
$artifactPath = Join-Path $OutputDirectory ("{0}.zip" -f $artifactBaseName)

if (Test-Path -LiteralPath $publishDirectory)
{
    Remove-Item -LiteralPath $publishDirectory -Recurse -Force
}

if (Test-Path -LiteralPath $packageDirectory)
{
    Remove-Item -LiteralPath $packageDirectory -Recurse -Force
}

if (Test-Path -LiteralPath $artifactPath)
{
    Remove-Item -LiteralPath $artifactPath -Force
}

New-Item -ItemType Directory -Path $publishDirectory -Force | Out-Null
New-Item -ItemType Directory -Path $packageDirectory -Force | Out-Null

dotnet publish $config.publishProject `
    --configuration $config.publishConfiguration `
    --runtime $config.runtimeIdentifier `
    --self-contained false `
    /p:UseAppHost=true `
    --output $publishDirectory

$publishedExecutables = @(Get-ChildItem -LiteralPath $publishDirectory -Filter *.exe -File)
if ($publishedExecutables.Count -eq 0)
{
    throw "The installer publish output did not contain any executable (*.exe) file."
}

Copy-Item -Path (Join-Path $publishDirectory "*") -Destination $packageDirectory -Recurse -Force

$readmePath = Join-Path $packageDirectory "INSTALLER-README.txt"
@(
    "OutreachFlow Installer Package",
    "",
    "Version: $Version",
    "Architecture: win-$($config.architecture)",
    "Runtime Identifier: $($config.runtimeIdentifier)",
    "",
    "This package is generated by scripts/release/Build-InstallerPackage.ps1."
) | Set-Content -LiteralPath $readmePath -Encoding UTF8

Compress-Archive -Path (Join-Path $packageDirectory "*") -DestinationPath $artifactPath -CompressionLevel Optimal

if (-not (Test-Path -LiteralPath $artifactPath))
{
    throw "Installer package was not generated."
}

$artifactInfo = Get-Item -LiteralPath $artifactPath
if ($artifactInfo.Length -le 0)
{
    throw "Installer package '$artifactPath' is empty."
}

Write-Host "Installer package generated successfully:"
Write-Host "  Path: $artifactPath"
Write-Host "  Size: $($artifactInfo.Length) bytes"
