using OutreachFlow.Application.Common; using OutreachFlow.Domain.Campaigns; using OutreachFlow.Domain.Common;
namespace OutreachFlow.Application.Campaigns;
public sealed class CampaignService(ICampaignRepository repository, IUnitOfWork unitOfWork) : ICampaignService
{ public async Task<IReadOnlyList<CampaignDto>> ListAsync(CancellationToken ct = default) { var items = await repository.ListAsync(ct); return await Task.WhenAll(items.Select(item => MapAsync(item, ct))); }
 public async Task<CampaignDto> GetAsync(Guid id, CancellationToken ct = default) => await MapAsync(await FindAsync(id, ct), ct);
 public async Task<CampaignDto> CreateAsync(CreateCampaignRequest request, CancellationToken ct = default) { Campaign item; try { item = new Campaign(request.Name); } catch (DomainException e) { throw new ApplicationValidationException(e.Message); } await repository.AddAsync(item, ct); await unitOfWork.SaveChangesAsync(ct); return await MapAsync(item, ct); }
 public async Task<CampaignDto> UpdateAsync(Guid id, UpdateCampaignRequest request, CancellationToken ct = default) { var item = await FindAsync(id, ct); try { item.UpdateDetails(request.Name, request.Subject, request.Body, request.SenderProfileId, request.FollowUpDueAt); } catch (DomainException e) { throw new ApplicationValidationException(e.Message); } await repository.ReplaceAsync(id, request.ContactIds.Distinct().Select(x => new CampaignContact(id,x)).ToArray(), request.ContactGroupIds.Distinct().Select(x => new CampaignContactGroup(id,x)).ToArray(), request.AttachmentAssetIds.Distinct().Select(x => new CampaignAttachment(id,x)).ToArray(), ct); await unitOfWork.SaveChangesAsync(ct); return await MapAsync(item,ct); }
 public async Task DeleteAsync(Guid id,CancellationToken ct=default) { repository.Remove(await FindAsync(id,ct)); await unitOfWork.SaveChangesAsync(ct); }
 private async Task<Campaign> FindAsync(Guid id,CancellationToken ct) => await repository.GetByIdAsync(id,ct) ?? throw new ApplicationNotFoundException("Campaign was not found.");
 private async Task<CampaignDto> MapAsync(Campaign item,CancellationToken ct) { var contacts=await repository.ContactsAsync(item.Id,ct); var groups=await repository.GroupsAsync(item.Id,ct); var attachments=await repository.AttachmentsAsync(item.Id,ct); var missing=new List<string>(); if(string.IsNullOrWhiteSpace(item.Subject)||string.IsNullOrWhiteSpace(item.Body))missing.Add("message"); if(item.SenderProfileId is null)missing.Add("sender"); if(contacts.Count==0&&groups.Count==0)missing.Add("recipients"); return new(item.Id,item.Name,item.Subject,item.Body,item.SenderProfileId,item.FollowUpDueAt,contacts.Select(x=>x.ContactId).ToArray(),groups.Select(x=>x.ContactGroupId).ToArray(),attachments.Select(x=>x.AttachmentAssetId).ToArray(),missing,item.CreatedAt,item.UpdatedAt); }
}
