// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutreachFlow.Infrastructure.Persistence;

#nullable disable

namespace OutreachFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OutreachFlowDbContext))]
    partial class OutreachFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");
#pragma warning restore 612, 618
        }
    }
}
